service: process-order-bff
frameworkVersion: '3'

custom:
  names:
    functions:
      storeRequest: ${self:service}-${sls:stage}-store-order-request
    sqs:
      storeOrderRequest: ${self:service}-${sls:stage}-store-order-request
provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: '*'
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:DeleteMessage
            - sqs:ReceiveMessage
            - sqs:GetQueueUrl
            - sqs:ListQueues
          Resource: '*'
  environment:
    SERVERLESS_STAGE_NAME: ${sls:stage}
    SERVERLESS_SERVICE_NAME: ${self:service}
functions:
  storeRequest:
    name: ${self:custom.names.functions.storeRequest}
    description: Store a public data from a front end on order receiving
    handler: api.storeRequestAPI
    environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED : 1
      NEST_SERVERLESS_APP_PROCESS_ORDER_QUEUE: ${ssm:/${self:service}/${sls:stage}/NEST_SERVERLESS_APP_PROCESS_ORDER_QUEUE}
    events:
      - httpApi:
          method: POST
          path: /process-order

plugins:
  - serverless-esbuild
  - serverless-offline
